@startuml

class Objeto {
    nombre
    posicion
    altura
}

class Sombra {
    longitud
    posicion
    direccion
}

class FuenteLuz {
    intensidad
    posicion
}

class Superficie {
    tipo
    posicion
}

Objeto "1" -- "0..*" Sombra : proyecta
FuenteLuz "1" -- "0..*" Sombra : produce
Sombra "1" -- "1" Superficie : se proyecta sobre

@enduml