@startuml

class Persona {
    nombre
}

class Interaccion {
    fecha
    tipo
    contexto
}

class Comportamiento {
    tipo
    intensidad
}

class Valoracion {
    puntuacion
    comentario
}

class Contexto {
    nombre
}

Persona "1" -- "0..*" Interaccion : participa en
Interaccion "1" -- "1" Contexto : ocurre en
Interaccion "1" -- "1..*" Comportamiento : muestra
Persona "1" -- "0..*" Valoracion : recibe
Persona "1" -- "0..*" Valoracion : realiza
Valoracion "*" --> "1" Persona : persona valorada

@enduml