@startuml

[*] --> PerteneceAlGrupo

PerteneceAlGrupo --> HaceGesto : 2. hacerGesto()
HaceGesto --> DaPuntos : 3. darPuntos()
DaPuntos --> AuraRecibePuntos : 4. recibirPuntos()

AuraRecibePuntos --> GrupoGrabaClip : 5. grabarClip()
GrupoGrabaClip --> ClipPublicado : 6. publicarEnRedes()

ClipPublicado --> RecibeValoracion : 7. recibirValoracion()
RecibeValoracion --> GeneraAdmiracion : 8. generarAdmiracion()
GeneraAdmiracion --> AuraAumenta : 9. aumentarAura()

AuraAumenta --> SeConvierteEnLeyenda : 10. convertirEnLeyenda()
SeConvierteEnLeyenda --> PersonaEsLeyenda : 11. hacerLeyenda()

PersonaEsLeyenda --> [*]

@enduml