@startuml

object "p : Persona" as p
object "g : GrupoDeAmigos" as g
object "ge : Gesto" as ge
object "pa : PuntosDeAura" as pa
object "a : Aura" as a
object "cl : Clip" as cl
object "r : RedesSociales" as r
object "v : Puntuación" as v
object "ad : Admiración" as ad
object "l : Leyenda" as l

p --> g : 1. perteneceAlGrupo()
p --> ge : 2. hacerGesto()
ge --> pa : 3. darPuntos()
pa --> a : 4. recibirPuntos()
g --> cl : 5. grabarClip()
cl --> r : 6. publicarEnRedes()
r --> v : 7. recibirPuntuacion()
v --> ad : 8. generarAdmiracion()
ad --> a : 9. aumentarAura()
a --> l : 10. convertirEnLeyenda()
l --> p : 11. hacerLeyenda()

@enduml